### ISSUE TITLE
Vehicle Fixing when lights turn on

### ISSUE THREAD

**Issue by ghost** [friendsincode/ELS-Plus#40]
When you turn the ELS on the vehicle, the vehicle fixes.

**Comment by JakeRyan1** [comment]
This is a known issue if you want to fix this for the time being please use the Canary channel
The repair fix has not been pushed out to the public yet but it is on their canary channel
To get the Canary channel you need to go to FiveM\FiveM.app\CitizenFX.ini then put in that file UpdateChannel=canary below your game path

**Comment by dexslab** [comment]
This issue has already been addressed and dealt with please make sure you read before posting issues thanks
