### ISSUE TITLE
Hud not working

### ISSUE THREAD

**Issue by JakeRyan1** [friendsincode/ELS-Plus#42]
I was testing some new cars today and I noticed when I turned the ELS control panel on the numbers were not changing while I was changing patterns, nor were the lights syncing on the panel. It seems to stop working when you have your lights on and exit the vehicle and get back in. here is a video https://youtu.be/cHh1b52w2pE I will keep this issue updated if I figure anything else out.

**Comment by dexslab** [comment]
Do you have baseevents running

**Comment by JakeRyan1** [comment]
Yes I have baseevents running

**Comment by dexslab** [comment]
This issue will be working on eventually

**Comment by dexslab** [comment]
HUD seems to work please double check base events thanks

**Comment by dexslab** [comment]
FIXED IT!!!! a long time ago
