### ISSUE TITLE
Add indicator control to the in settings

### ISSUE THREAD

**Issue by ejb1123** [friendsincode/ELS-Plus#57]
Add the ability to enable or disable the indicators based on settings in the ini

**Comment by dexslab** [comment]
Blah

**Comment by xXcarlos117Xx2** [comment]
+1, i already have a indicator plugins

**Comment by Virrefirre** [comment]
-1
Just set the indicator key to 65 (INPUT_VEH_SPECIAL)

INPUT_VEH_SPECIAL = None on both Default QWERTY and Xbox Controller

**Comment by xXcarlos117Xx2** [comment]
Thank you it works

**Comment by Virrefirre** [comment]
No problem! =)
