### ISSUE TITLE
Bug and a suggestion:

### ISSUE THREAD

**Issue by Sharquisha** [friendsincode/ELS-Plus#61]
Currently for the bug you cannot enter the map using P or the Start Button(xbox) when in a ELS vehicle.

And for a suggestion add a way to use B Button(xbox) to cycle through sirens when in LS3 and blip your siren when not in LS3(in LS2, LS1, and none).

A question: The walls and grass seem to light up, but the ground doesnt. I dont know if thats a bug or something with my visual mod.

Thank you.

**Comment by dexslab** [comment]
Please copy and paste this issue to the gitlab thanks 😄 
https://git.friendsincode.com
