### ISSUE TITLE
Latest Release Bugs:

### ISSUE THREAD

**Issue by Detoxz** [friendsincode/ELS-Plus#68]
UI on start stays opened and will not close.
ELS Vehicles not being detected even with is_els = true at the bottom of a resource lua. Had no issues with previous version, only latest update found on the git page

**Comment by Detoxz** [comment]
![image](https://user-images.githubusercontent.com/41855089/44315422-ee952e00-a3f1-11e8-94e4-4b6cc035e99d.png)
elslist does not display ELS vehicles.
Elsui doesn't close the ui opened up

**Comment by Detoxz** [comment]
using version 0.0.32
![image](https://user-images.githubusercontent.com/41855089/44315514-f2758000-a3f2-11e8-97aa-c386db7a2f4e.png)

**Comment by dexslab** [comment]
You have an error client side you need to fix this is what is causing the error

**Comment by dexslab** [comment]
You also need to move to build #72 which is located on out Gitlab as we have migrated from Github

**Comment by Detoxz** [comment]
i'm using the latest build on the gitlab. I've resolved my own issue and closed this myself for a reason. There was no errors client or server side though c:
