### ISSUE TITLE
Console Spam due to leftovers of deleted vehicles and non networked vehicles causing lag and console spam

### ISSUE THREAD

**Issue by niekschoemaker** [friendsincode/ELS-Plus#72]
Whenever a vehicle is suddenly deleted (not sure if the same case is true for exploded vehicles) by for example esx_jobs it seems to not realise the vehicle is gone and after a while it starts massively spamming the console quite a bit.
Another issue is with certain garage plugins which don't network the cars to other players (ESX has commands built in to spawn only locally) and this causes massive lag because of the amount of console spam the errors produce because it tries to get a non existent network ID, I tried fixing it myself with NetworkGetEntityIsNetworked() but didn't really know where to put the checks exactly so just ended up causing more and more issues with NullPointers.
I'm running the latest builds from the dev branch from the friendsincode (https://git.friendsincode.com/PFM/ELS-Plus/tree/dev) couldn't send an issue there without an account so did it here instead.

**Comment by dexslab** [comment]
Discord is one of the best places to go for help and it will allow us to better assist u with fixing those errors

**Comment by niekschoemaker** [comment]
Just wondering, what discord are you referring here? Since the discord link is missing in the readme (could find one of the old maintainer of ELS FiveM but not on this one)
