### ISSUE TITLE
git credentials?

### ISSUE THREAD

**Issue by mickeygeecom** [friendsincode/ELS-Plus#76]
Im trying to do: `git clone https://git.friendsincode.com/PFM/ELS-Plus.git` and I get prompted for credentials, which I can't see anywhere which is? :)

And why is there not a pre-build version just to grab?

**Comment by dexslab** [comment]
That is because u are trying to pull from our website and not GitHub if u go to https://git.friendsincode.com/dexslab/elsplus u can download a prebuilt version of els plus

**Comment by mickeygeecom** [comment]
I just downloaded it from git, and build it. I'm reporting a bug in a moment though.
