### ISSUE TITLE
[v0.0.4.1] Police Lights Laggy and Blimping of Siren

### ISSUE THREAD

**Issue by ghost** [friendsincode/ELS-Plus#8]
https://youtu.be/aFfrnvCUaX8

**Comment by ejb1123** [comment]
This is probably due to the client sending data of the extra over the network. A memory mod to disable the transmission of such data should help to solve this issue.

 ------

Blipping Siren is being looked into.

**Comment by ejb1123** [comment]
@xrayhunter1 What other mods where running on the server at that time of testing?

**Comment by dexslab** [comment]
Need all client side mods as well as what is installed server side please

**Comment by dexslab** [comment]
This issue is no longer present if it comes back up please post another issue report
