### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by larscrazynl** [friendsincode/ELS-Plus#83]
I've got everything set up and installed properly. Screens from one of my cars:

**But we get this error in the console/chat:**
"Instantiated instance of script ELS_Server.Class1."

**And 2 different errors in the F8 console:**
https://imgur.com/a/ABJ4nJq

How do I fix this because some cars don't work well either

Can this be solved?
Or do you have to use the new version, but I don't know how to convert a source code to a release.

**Comment by dexslab** [comment]
Our discord has latest release you can find it in the support channel pinned posts

**Comment by larscrazynl** [comment]
Hey, how can i join your discord because there is no link in de readme. Where can i find it?
https://imgur.com/a/fBtIwWr
