### ISSUE TITLE
[v0.0.4.1] UI stays after jumping out of the vehicle

### ISSUE THREAD

**Issue by ghost** [friendsincode/ELS-Plus#9]
This has to deal with, how the UI is being handled.

**Comment by dexslab** [comment]
The UI should drop out when you exit a non ELS vehicle

**Comment by dexslab** [comment]
Will be fixed in next push from me, thanks

**Comment by ghost** [comment]
I pull requested a patch for this.

**Comment by dexslab** [comment]
There is no pull request but its already fixed in my code it will be pushed soon

**Comment by ghost** [comment]
Okay. Closing Thread.
