### ISSUE TITLE
I can’t start els-plus.

### ISSUE THREAD

**Issue by GabinGrobost** [friendsincode/ELS-Plus#90]
I can’t start els-plus I followed all the instructions but I couldn’t, because I can’t find the __resource.lua in els-plus.
You can help me?

**Comment by GabinGrobost** [comment]
@dexslab

**Comment by josh-tf** [comment]
Download from releases, not the repository
If you download the repository you will need to build it yourself

**Comment by izmystic** [comment]
You had too add the ELS files to the __resource.lua of one of the vehicles
like so
![Screenshot 2021-02-18 031711](https://user-images.githubusercontent.com/72127044/108326065-cf7ce000-7197-11eb-8885-02948ed2a7ef.png)

**Comment by dexslab** [comment]
Please join our discord for the latest release and proper support
